### Generated by Winemaker 0.8.3
###
### Invocation command line was
### /usr/bin/winemaker --lower-uppercase --mfc .


SRCDIR                = .
SUBDIRS               = ScriptEngine
DLLS                  =
LIBS                  =
EXES                  = byakhee



### Common settings

CEXTRA                = -mno-cygwin -fpermissive
CXXEXTRA              = -mno-cygwin -fpermissive
RCEXTRA               =
DEFINES               =
INCLUDE_PATH          = -I. \
			$(MFC_INCLUDE_PATH)
DLL_PATH              =
DLL_IMPORTS           =
LIBRARY_PATH          =
LIBRARIES             =


### byakhee sources and settings

byakhee_MODULE        = byakhee
byakhee_C_SRCS        =
byakhee_CXX_SRCS      = AboutDlg.cpp \
			AddSkillDlg.cpp \
			Byakhee.cpp \
			ByakheeScriptExecutor.cpp \
			CharacterAgeDlg.cpp \
			ChildFrm.cpp \
			ChooseSkillDlg.cpp \
			ColouredListBox.cpp \
			DiceRoller.cpp \
			DragSwapEdit.cpp \
			EditSkillDlg.cpp \
			EditSkillsDlg.cpp \
			EditWeaponsDlg.cpp \
			Field.cpp \
			FieldEdit.cpp \
			HandoutDoc.cpp \
			HandoutView.cpp \
			Hyperlink.cpp \
			Investigator.cpp \
			InvestigatorPopupWnd.cpp \
			MDIWnd.cpp \
			MainFrm.cpp \
			MultiFileMultiDocTemplate.cpp \
			NamedOptionManager.cpp \
			NewDocumentDlg.cpp \
			NewWeaponDlg.cpp \
			OptionalSkillsDlg.cpp \
			OptionsDlg.cpp \
			OptionsPages.cpp \
			Output.cpp \
			ParseBuffer.cpp \
			PopupWnd.cpp \
			QuickInfoDlg.cpp \
			RandomNameGenerator.cpp \
			ScriptEditDoc.cpp \
			ScriptEditView.cpp \
			ScriptSheetView.cpp \
			SectionFile.cpp \
			SheetCommand.cpp \
			SheetDrawInfo.cpp \
			Skill.cpp \
			SkillEditListBox.cpp \
			SkillInformationPopupWnd.cpp \
			SkillManager.cpp \
			SpellbookDlg.cpp \
			Splash.cpp \
			Wizard_NewInvestigator.cpp \
			Wizard_NewInvestigatorPages.cpp \
			investigatordoc.cpp \
			investigatorview.cpp \
			sizecbar.cpp
byakhee_RC_SRCS       = Byakhee.rc
byakhee_LDFLAGS       = -mwindows \
			-mno-cygwin
byakhee_ARFLAGS       =
byakhee_DLL_PATH      = $(MFC_LIBRARY_PATH)
byakhee_DLLS          = odbc32 \
			ole32 \
			oleaut32 \
			winspool \
			odbccp32 \
			mfc.dll
byakhee_LIBRARY_PATH  = $(MFC_LIBRARY_PATH)
byakhee_LIBRARIES     = uuid \
			mfc

byakhee_OBJS          = $(byakhee_C_SRCS:.c=.o) \
			$(byakhee_CXX_SRCS:.cpp=.o) \
			$(byakhee_RC_SRCS:.rc=.res)



### Global source lists

C_SRCS                = $(byakhee_C_SRCS)
CXX_SRCS              = $(byakhee_CXX_SRCS)
RC_SRCS               = $(byakhee_RC_SRCS)


### Tools

CC = winegcc
CXX = wineg++
RC = wrc
AR = ar


### Generic targets

all: $(SUBDIRS) $(DLLS:%=%.so) $(LIBS) $(EXES)

### Build rules

.PHONY: all clean dummy

$(SUBDIRS): dummy
	@cd $@ && $(MAKE)

# Implicit rules

.SUFFIXES: .cpp .cxx .rc .res
DEFINCL = $(INCLUDE_PATH) $(DEFINES) $(OPTIONS)

.c.o:
	$(CC) -c $(CFLAGS) $(CEXTRA) $(DEFINCL) -o $@ $<

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(CXXEXTRA) $(DEFINCL) -o $@ $<

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(CXXEXTRA) $(DEFINCL) -o $@ $<

.rc.res:
	$(RC) $(RCFLAGS) $(RCEXTRA) $(DEFINCL) -fo$@ $<

# Rules for cleaning

CLEAN_FILES     = y.tab.c y.tab.h lex.yy.c core *.orig *.rej \
                  \\\#*\\\# *~ *% .\\\#*

clean:: $(SUBDIRS:%=%/__clean__) $(EXTRASUBDIRS:%=%/__clean__)
	$(RM) $(CLEAN_FILES) $(RC_SRCS:.rc=.res) $(C_SRCS:.c=.o) $(CXX_SRCS:.cpp=.o)
	$(RM) $(DLLS:%=%.so) $(LIBS) $(EXES) $(EXES:%=%.so)

$(SUBDIRS:%=%/__clean__): dummy
	cd `dirname $@` && $(MAKE) clean

$(EXTRASUBDIRS:%=%/__clean__): dummy
	-cd `dirname $@` && $(RM) $(CLEAN_FILES)

### Target specific build rules
DEFLIB = $(LIBRARY_PATH) $(LIBRARIES) $(DLL_PATH) $(DLL_IMPORTS:%=-l%)

$(byakhee_MODULE): $(byakhee_OBJS)
	$(CXX) $(byakhee_LDFLAGS) -o $@ $(byakhee_OBJS) $(byakhee_LIBRARY_PATH) $(DEFLIB) $(byakhee_DLLS:%=-l%) $(byakhee_LIBRARIES:%=-l%)


